//
// Photo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Photo: JSONEncodable {
    public var height: Int32?
    public var width: Int32?
    public var photoReference: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["height"] = self.height?.encodeToJSON()
        nillableDictionary["width"] = self.width?.encodeToJSON()
        nillableDictionary["photo_reference"] = self.photoReference
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
