//
// Place.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import CoreLocation

open class Place: JSONEncodable {
    public var id: String?
    public var placeId: String?
    public var geometry: Geometry?
    public var scope: String?
    public var rating: Double?
    public var vicinity: String?
    public var types: [String]?
    public var name: String?
    public var photos: [Photo]?

    public init() {}
    
    public func distanceOf(coordinate: CLLocation) -> Double {
        let coordinatePlace = CLLocation(latitude: (geometry?.location?.lat)!, longitude: (geometry?.location?.lng)!)
        return coordinate.distance(from: coordinatePlace)
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["place_id"] = self.placeId
        nillableDictionary["geometry"] = self.geometry?.encodeToJSON()
        nillableDictionary["scope"] = self.scope
        nillableDictionary["rating"] = self.rating
        nillableDictionary["vicinity"] = self.vicinity
        nillableDictionary["types"] = self.types?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["photos"] = self.photos?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
